[package]
name = "hexencer-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
midir = "0.10.0"
eframe = "0.27.2"

## workspace
tokio = {workspace=true}
tracing = {workspace=true}
tracing-subscriber = {workspace=true}

## internal libs
hexencer-core={path="../core"}
